package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;




/**
 * CantidadmrId generated by hbm2java
 */
@Embeddable
public class CantidadmrId  implements java.io.Serializable {

    @Column(name = "idreceta")
     private Integer idreceta;
    @Column(name = "idmaterial")
     private Integer idmaterial;

    public CantidadmrId() {
    }

    public CantidadmrId(Integer idreceta, Integer idmaterial) {
       this.idreceta = idreceta;
       this.idmaterial = idmaterial;
    }
   
    public Integer getIdreceta() {
        return this.idreceta;
    }
    
    public void setIdreceta(Integer idreceta) {
        this.idreceta = idreceta;
    }
    public Integer getIdmaterial() {
        return this.idmaterial;
    }
    
    public void setIdmaterial(int idmaterial) {
        this.idmaterial = idmaterial;
    }

    public void setIdmaterial(Integer idmaterial) {
        this.idmaterial = idmaterial;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CantidadmrId) ) return false;
		 CantidadmrId castOther = ( CantidadmrId ) other; 
         
		 return (this.getIdreceta()==castOther.getIdreceta())
 && (this.getIdmaterial()==castOther.getIdmaterial());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdreceta();
         result = 37 * result + this.getIdmaterial();
         return result;
   }   


}


