package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;




/**
 * CantidadmpId generated by hbm2java
 */
@Embeddable
public class CantidadmpId  implements java.io.Serializable {

    @Column(name = "idpedido")
     private Integer idpedido;
    @Column(name = "idmaterial")
     private Integer idmaterial;
    
    public CantidadmpId() {
    }

    public CantidadmpId(Integer idpedido, Integer idmaterial) {
       this.idpedido = idpedido;
       this.idmaterial = idmaterial;
    }
   
    public Integer getIdpedido() {
        return this.idpedido;
    }
    
    public void setIdpedido(Integer idpedido) {
        this.idpedido = idpedido;
    }
    public Integer getIdmaterial() {
        return this.idmaterial;
    }
    
    public void setIdmaterial(Integer idmaterial) {
        this.idmaterial = idmaterial;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CantidadmpId) ) return false;
		 CantidadmpId castOther = ( CantidadmpId ) other; 
         
		 return (this.getIdpedido()==castOther.getIdpedido())
 && (this.getIdmaterial()==castOther.getIdmaterial());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdpedido();
         result = 37 * result + this.getIdmaterial();
         return result;
   }   


}


