package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.MapsId;
import javax.persistence.Table;




/**
 * Cantidadmp generated by hbm2java
 */

@Entity(name = "Cantidadmp")
@Table(name = "cantidadmp")
public class Cantidadmp implements java.io.Serializable {

     @EmbeddedId
     private CantidadmpId id;
     @Column(name = "cantidad")
     private int cantidad;
     @ManyToOne(fetch = FetchType.LAZY)
     @MapsId("idpedido")
     private Pedidos pedido;
     @ManyToOne(fetch = FetchType.LAZY)
     @MapsId("idmaterial")
     private Material material;
    
    public Cantidadmp() {
    }

    public Cantidadmp(Pedidos pedido, Material material, int cantidad) {
       this.id = new CantidadmpId(pedido.getIdpedido(), material.getIdmaterial());
       this.cantidad = cantidad;
       this.pedido = pedido;
       this.material = material;
    }
   
    public CantidadmpId getId() {
        return this.id;
    }
    
    public void setId(CantidadmpId id) {
        this.id = id;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public Pedidos getPedido() {
        return pedido;
    }

    public void setPedido(Pedidos pedido) {
        this.pedido = pedido;
    }


    public Material getMaterial() {
        return material;
    }

    public void setMaterial(Material material) {
        this.material = material;
    }

}


