package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ejecucion generated by hbm2java
 */

@Entity(name = "Ejecucion")
@Table(name = "ejecucion")
public class Ejecucion  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idrenglon;
    @Column(name = "fechaalta")
     private Date fechaalta;
    @Column(name = "fechainicio")
     private Date fechainicio;
    @Column(name = "fechafin")
     private Date fechafin;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="idRecurso")
     private Recurso recurso;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="idLote")
     private Lotedeproduccion lotedeproduccion;
    @OneToMany(mappedBy = "ejecucion",cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Estadodeejecucion> estadosDeEjecucion = new HashSet<Estadodeejecucion>();

    public Ejecucion() {
    }

    public Ejecucion(Integer idrenglon, Date fechaalta, Date fechainicio, Date fechafin, Recurso recurso, Lotedeproduccion lotedeproduccion) {
       this.idrenglon = idrenglon;
       this.fechaalta = fechaalta;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.recurso = recurso;
       this.lotedeproduccion = lotedeproduccion;
    }
   
    public Integer getIdrenglon() {
        return this.idrenglon;
    }
    
    public void setIdrenglon(Integer idrenglon) {
        this.idrenglon = idrenglon;
    }
    public Date getFechaalta() {
        return this.fechaalta;
    }
    
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

    public Recurso getRecurso() {
        return recurso;
    }

    public void setRecurso(Recurso recurso) {
        this.recurso = recurso;
    }

    public Lotedeproduccion getLotedeproduccion() {
        return lotedeproduccion;
    }

    public void setLotedeproduccion(Lotedeproduccion lotedeproduccion) {
        this.lotedeproduccion = lotedeproduccion;
    }

    public Set<Estadodeejecucion> getEstadosDeEjecucion() {
        return estadosDeEjecucion;
    }

    public void setEstadosDeEjecucion(Set<Estadodeejecucion> estadosDeEjecucion) {
        this.estadosDeEjecucion = estadosDeEjecucion;
    }


}


