package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Estadodeejecucion generated by hbm2java
 */

@Entity(name = "Estadodeejecucion")
@Table(name = "estadodeejecucion")
public class Estadodeejecucion  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idestado;
     @Column(name = "fechaalta")
     private Date fechaalta;
     @Column(name = "estado")
     private String estado;
     @Column(name = "reporte")
     private String reporte;
     @ManyToOne(fetch = FetchType.LAZY)
     @JoinColumn(name="idRenglon")
     private Ejecucion ejecucion;

    public Estadodeejecucion() {
    }

    public Estadodeejecucion(Integer idestado, Date fechaalta, String estado, String reporte, Ejecucion ejecucion) {
       this.idestado = idestado;
       this.fechaalta = fechaalta;
       this.estado = estado;
       this.reporte = reporte;
       this.ejecucion = ejecucion;
    }
   
    public Integer getIdestado() {
        return this.idestado;
    }
    
    public void setIdestado(Integer idestado) {
        this.idestado = idestado;
    }
    public Date getFechaalta() {
        return this.fechaalta;
    }
    
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getReporte() {
        return this.reporte;
    }
    
    public void setReporte(String reporte) {
        this.reporte = reporte;
    }

    public Ejecucion getEjecucion() {
        return ejecucion;
    }

    public void setEjecucion(Ejecucion ejecucion) {
        this.ejecucion = ejecucion;
    }


}


