package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estaciones generated by hbm2java
 */

@Entity(name = "Estaciones")
@Table(name = "estaciones")
public class Estaciones  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idestaciones;
    @Column(name = "nombre")
     private String nombre;
    @Column(name = "ubicacion")
     private String ubicacion;
    @Column(name = "descripcion")
     private String descripcion;
    @Column(name = "fechaalta")
     private Date fechaalta;
    @Column(name = "fechabaja")
     private Date fechabaja;
    @OneToMany(mappedBy = "estacion", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Recurso> recursos = new HashSet<Recurso>();

    public Estaciones() {
    }

    public Estaciones(Integer idestaciones, String nombre, String ubicacion, String descripcion, Date fechaalta, Date fechabaja) {
       this.idestaciones = idestaciones;
       this.nombre = nombre;
       this.ubicacion = ubicacion;
       this.descripcion = descripcion;
       this.fechaalta = fechaalta;
       this.fechabaja = fechabaja;
    }
   
    public Integer getIdestaciones() {
        return this.idestaciones;
    }
    
    public void setIdestaciones(Integer idestaciones) {
        this.idestaciones = idestaciones;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaalta() {
        return this.fechaalta;
    }
    
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }
    public Date getFechabaja() {
        return this.fechabaja;
    }
    
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }

    public Set<Recurso> getRecursos() {
        return recursos;
    }

    public void setRecursos(Set<Recurso> recursos) {
        this.recursos = recursos;
    }

}


