package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;




/**
 * Lotedeproduccion generated by hbm2java
 */
@Entity(name = "Lotedeproduccion")
@Table(name = "lotedeproduccion")
public class Lotedeproduccion  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idlote;
    
    @Column(name = "numerolote")
     private Integer numerolote;
    
    @OneToMany(mappedBy = "lotedeproduccion",cascade = {CascadeType.ALL})
    private List<Productosproducidos> productosProducidos = new ArrayList<>();
    
    @OneToMany(mappedBy = "lotedeproduccion",cascade = {CascadeType.ALL})
    private List<Ejecucion> ejecuciones = new ArrayList<>();
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="idProducto")
    private Producto producto;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name="idPlan")
    private Planproduccion planProduccion;

    public Lotedeproduccion() {
    }

    public Lotedeproduccion(Integer idlote, Integer numerolote, Producto producto, Planproduccion planProduccion) {
       this.idlote = idlote;
       this.numerolote = numerolote;
    }
   
    public Integer getIdlote() {
        return this.idlote;
    }
    
    public void setIdlote(Integer idlote) {
        this.idlote = idlote;
    }
    public Integer getNumerolote() {
        return this.numerolote;
    }
    
    public void setNumerolote(Integer numerolote) {
        this.numerolote = numerolote;
    }

    public List<Productosproducidos> getProductosProducidos() {
        return productosProducidos;
    }

    public void setProductosProducidos(List<Productosproducidos> productosProducidos) {
        this.productosProducidos = productosProducidos;
    }
    
    public void addProductosProducidos(Productosproducidos productosProducidos) {
        this.productosProducidos.add(productosProducidos);
    }

    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public Planproduccion getPlanProduccion() {
        return planProduccion;
    }

    public void setPlanProduccion(Planproduccion planProduccion) {
        this.planProduccion = planProduccion;
    }

    public List<Ejecucion> getEjecuciones() {
        return ejecuciones;
    }

    public void setEjecuciones(List<Ejecucion> ejecuciones) {
        this.ejecuciones = ejecuciones;
    }

    
}


