package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Material generated by hbm2java
 */

@Entity(name = "Material")
@Table(name = "material")
public class Material  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idmaterial;
    @Column(name = "nombre")
     private String nombre;
    @Column(name = "fechaalta")
     private Date fechaalta;
    @Column(name = "fechabaja")
     private Date fechabaja;
    @Column(name = "unidad")
     private String unidad;
    @Column(name = "cantidadminima")
     private double cantidadminima;
    @OneToMany(mappedBy = "material",cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Cantidadmp> pedidos = new ArrayList<>();
    @OneToMany(mappedBy = "material",cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Cantidadmr> recetas = new ArrayList<>();
    
    public Material() {
    }

    public Material(Integer idmaterial, String nombre, Date fechaalta, Date fechabaja, String unidad, double cantidadminima) {
       this.idmaterial = idmaterial;
       this.nombre = nombre;
       this.fechaalta = fechaalta;
       this.fechabaja = fechabaja;
       this.unidad = unidad;
       this.cantidadminima = cantidadminima;
    }
   
    public Integer getIdmaterial() {
        return this.idmaterial;
    }
    
    public void setIdmaterial(Integer idmaterial) {
        this.idmaterial = idmaterial;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaalta() {
        return this.fechaalta;
    }
    
    public void setFechaalta(Date fechaalta) {
        this.fechaalta = fechaalta;
    }
    public Date getFechabaja() {
        return this.fechabaja;
    }
    
    public void setFechabaja(Date fechabaja) {
        this.fechabaja = fechabaja;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public double getCantidadminima() {
        return this.cantidadminima;
    }
    
    public void setCantidadminima(double cantidadminima) {
        this.cantidadminima = cantidadminima;
    }

    public List<Cantidadmp> getPedidos() {
        return pedidos;
    }

    public void setPedidos(List<Cantidadmp> pedidos) {
        this.pedidos = pedidos;
    }

    public List<Cantidadmr> getRecetas() {
        return recetas;
    }

    public void setRecetas(List<Cantidadmr> recetas) {
        this.recetas = recetas;
    }



}


