package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Planproduccion generated by hbm2java
 */

@Entity(name = "Planproduccion")
@Table(name = "planproduccion")
//@NaturalIdCache
//@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Planproduccion  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idplan;
    @Column(name = "ordendeproduccion")
     private String ordendeproduccion;
    @Column(name = "fechacreacion")
     private Date fechacreacion;
    @Column(name = "fechainicioestimada")
     private Date fechainicioestimada;
    @Column(name = "fechafinestimada")
     private Date fechafinestimada;
    @Column(name = "descripcion")
     private String descripcion;
    @OneToMany(mappedBy = "planProduccion",cascade = CascadeType.ALL)
     private List<Pedidos> pedidos = new ArrayList<>();
    @OneToMany(mappedBy = "planProduccion", cascade = {CascadeType.ALL})
     private List<Lotedeproduccion> lotedeproduccion = new ArrayList<>();
    @OneToMany(mappedBy = "planProduccion",cascade = CascadeType.ALL)
     private List<Cantidadproductos> productos = new ArrayList<>();
    
    public Planproduccion() {
        this.fechacreacion = new Date();
    }

    public Planproduccion(String ordendeproduccion, Date fechainicioestimada, Date fechafinestimada, String descripcion) {
       this.ordendeproduccion = ordendeproduccion;
       this.fechainicioestimada = fechainicioestimada;
       this.fechafinestimada = fechafinestimada;
       this.descripcion = descripcion;
       this.fechacreacion = new Date();
    }
   
    public Integer getIdplan() {
        return this.idplan;
    }
    
    public void setIdplan(Integer idplan) {
        this.idplan = idplan;
    }
    public String getOrdendeproduccion() {
        return this.ordendeproduccion;
    }
    
    public void setOrdendeproduccion(String ordendeproduccion) {
        this.ordendeproduccion = ordendeproduccion;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public Date getFechainicioestimada() {
        return this.fechainicioestimada;
    }
    
    public void setFechainicioestimada(Date fechainicioestimada) {
        this.fechainicioestimada = fechainicioestimada;
    }
    public Date getFechafinestimada() {
        return this.fechafinestimada;
    }
    
    public void setFechafinestimada(Date fechafinestimada) {
        this.fechafinestimada = fechafinestimada;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public List<Pedidos> getPedidos() {
        return pedidos;
    }

    public void addPedido(Pedidos pedidos) {
        this.pedidos.add(pedidos);
    }

    public List<Cantidadproductos> getProductos() {
        return productos;
    }

    public void addProducto(Producto producto, Integer cantidad) {
        Cantidadproductos newProducto = new Cantidadproductos(this, producto, cantidad);
        this.productos.add(newProducto);
    }

    public List<Lotedeproduccion> getLotedeproduccion() {
        return lotedeproduccion;
    }

    public void addLotedeproduccion(Lotedeproduccion lotedeproduccion) {
        this.lotedeproduccion.add(lotedeproduccion);
    }

}


