package com.produccion.entities;
// Generated 24/09/2018 13:27:46 by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;




/**
 * Productosproducidos generated by hbm2java
 */

@Entity(name = "Productosproducidos")
@Table(name = "productosproducidos")
public class Productosproducidos  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
     private Integer idpproducido;
    @Column(name = "numeroseries")
     private int numeroserie;
    @Column(name = "desensamble")
     private Boolean desensamble;
    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinColumn(name = "idlote")
     private Lotedeproduccion lotedeproduccion;

    public Productosproducidos() {
        this.desensamble = false;
    }

	
    public Productosproducidos(Integer idpproducido, int numeroserie, Lotedeproduccion otedeproduccion) {
        this.idpproducido = idpproducido;
        this.numeroserie = numeroserie;
        this.lotedeproduccion = otedeproduccion;
    }
    public Productosproducidos(Integer idpproducido, int numeroserie, Boolean desensamble, Lotedeproduccion otedeproduccion) {
       this.idpproducido = idpproducido;
       this.numeroserie = numeroserie;
       this.desensamble = desensamble;
       this.lotedeproduccion = otedeproduccion;
    }
   
    public Integer getIdpproducido() {
        return this.idpproducido;
    }
    
    public void setIdpproducido(Integer idpproducido) {
        this.idpproducido = idpproducido;
    }
    public int getNumeroserie() {
        return this.numeroserie;
    }
    
    public void setNumeroserie(int numeroserie) {
        this.numeroserie = numeroserie;
    }
    public Boolean getDesensamble() {
        return this.desensamble;
    }
    
    public void setDesensamble(Boolean desensamble) {
        this.desensamble = desensamble;
    }

    public Lotedeproduccion getOtedeproduccion() {
        return lotedeproduccion;
    }

    public void setOtedeproduccion(Lotedeproduccion otedeproduccion) {
        this.lotedeproduccion = otedeproduccion;
    }

    public Lotedeproduccion getLotedeproduccion() {
        return lotedeproduccion;
    }

    public void setLotedeproduccion(Lotedeproduccion lotedeproduccion) {
        this.lotedeproduccion = lotedeproduccion;
    }

}


